#  AUTH = echo -n <your-github-username>:<TOKEN> | base64
kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: github-container-registry-secret
stringData:
  .dockerconfigjson: {"auths":{"docker.pkg.github.com":{"auth":"<AUTH>"}}}