name: publish docker on main

on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: fastapi_template

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.CONTAINER_REGISTRY_PAT }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      - run: make docker-push