name: test application

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'poetry'
    - name: Installing dependencies
      run: poetry install
    - name: Checking linting, formatting and security
      run: make check-all
    - name: Running tests
      run: make test-all
